# Generated by Django 6.0 on 2025-12-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата до')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта')),
                ('work_mode', models.CharField(blank=True, choices=[('office', 'В офисе'), ('remote', 'Удаленно'), ('hybrid', 'Гибрид')], max_length=20, null=True, verbose_name='Режим работы')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='Ссылка на вакансию')),
                ('external_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ID вакансии')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-posted_at'],
                'indexes': [models.Index(fields=['title'], name='parserapp_v_title_2ca525_idx'), models.Index(fields=['company_name'], name='parserapp_v_company_d0a847_idx'), models.Index(fields=['location'], name='parserapp_v_locatio_e3f5da_idx')],
            },
        ),
    ]
