"""
Django settings for myparser project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Директория проекта (где лежит manage.py и .env)
PROJECT_DIR = BASE_DIR


# --- .env loader (без внешних зависимостей) ---
def _load_env(env_path: Path):
    if not env_path.exists():
        return False
    try:
        content = env_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        # На случай, если файл сохранён в UTF-16/1251 и т.п.
        content = env_path.read_text(encoding="utf-16", errors="ignore")
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key, value = key.strip(), value.strip()
        # убираем возможный BOM
        key = key.lstrip("\ufeff")
        # убираем кавычки по краям, если есть
        if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
            value = value[1:-1]
        # перезаписываем значение из .env даже если переменная окружения уже существует
        os.environ[key] = value
    return True


# Пробуем загрузить .env из нескольких типичных мест (используем прямой путь)
_env_loaded = _load_env(PROJECT_DIR / ".env")
if not _env_loaded:
    _env_loaded = _load_env(BASE_DIR / ".env")
if not _env_loaded:
    _env_loaded = _load_env(BASE_DIR.parent / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    # дополнительная попытка достать SECRET_KEY прямо из файла .env (используем прямой путь)
    for candidate in (PROJECT_DIR / ".env", BASE_DIR / ".env", BASE_DIR.parent / ".env"):
        if candidate.exists():
            try:
                content = candidate.read_text(encoding="utf-8", errors="ignore")
            except Exception:
                try:
                    content = candidate.read_text(encoding="utf-16", errors="ignore")
                except Exception:
                    continue
            for line in content.splitlines():
                line_orig = line
                line = line.strip()
                # Убираем BOM если есть
                if line.startswith('\ufeff'):
                    line = line[1:]
                if line.startswith("SECRET_KEY") or line.startswith("SECRET_KEY="):
                    try:
                        if "=" in line:
                            _, value = line.split("=", 1)
                        else:
                            continue
                        value = value.strip().strip('"').strip("'")
                        if value:
                            SECRET_KEY = value
                            os.environ['SECRET_KEY'] = value
                            break
                    except Exception:
                        continue
        if SECRET_KEY:
            break
if not SECRET_KEY:
    env_paths = [PROJECT_DIR / ".env", BASE_DIR / ".env", BASE_DIR.parent / ".env"]
    existing = [str(p) for p in env_paths if p.exists()]
    msg = f"SECRET_KEY is not set. Define it in .env file.\nChecked paths: {env_paths}\nExisting .env files: {existing}"
    raise ImproperlyConfigured(msg)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = [h for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h] if os.getenv('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'parserapp',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'parserapp.middleware.DisableCSRFForAPI',  # Отключает CSRF для API endpoints
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myparser.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myparser.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}
